name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '5 16 * * 4'
workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        echo "Running!"
